server.port=8000
spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/nethmidilekshakavi/config-server
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

eureka.client.service-url.defaultZone=http://34.47.225.165:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30